kind: pipeline
branch: ^master$
jenkins: apps
triggers:
  gitpush: true
pipeline:
  extensions:
    github:
  steps:
  - docker:
      build:
        image: fareoffice/modsecurity:3-nginx-${GIT_COMMIT}
      tag:
      - fareoffice/modsecurity:3-nginx
      push: true
