kind: pipeline
jenkins: apps
branch: ^master$
parameters:
  INCREMENT: ["patch", "minor", "major"]
pipeline:
  extensions:
    githubRelease:
      channel: infra-releases
      image: fareoffice/modsecurity:3-nginx-${GIT_COMMIT}
